# Generated by Django 3.2.5 on 2021-08-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app9', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermarketsale',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
