# Generated by Django 3.2.5 on 2021-08-31 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app9', '0002_supermarketsale_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='supermarketsale',
        ),
    ]
