# Generated by Django 3.2.5 on 2021-08-18 06:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='student_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 6, 30, 46, 955919, tzinfo=utc)),
        ),
    ]
