# Generated by Django 3.2.5 on 2021-08-31 07:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_post_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='student_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 7, 21, 15, 94905, tzinfo=utc)),
        ),
    ]
